name: AndroidBuild

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Set Gradle Properties
        run: echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> ~/.gradle/gradle.properties

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --debug

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Build Logs
          path: app/build/reports
